version: "3.9"

services:
  # 🌐 NGINX — API Gateway
  nginx:
    container_name: nginx_gateway
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # внешний доступ к API
    networks:
      - crm-network
    depends_on:
      - auth-service
      - user-service
      - lead-service
      - task-service
      - file-service
      - frontend-develop

    # 🌐 FRONTEND — Веб-приложение (Vue.js)
  frontend-develop:
    container_name: frontend_develop
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/crm-app/:/app
    networks:
      - crm-network

  # 🔐 AUTH SERVICE — Аутентификация и JWT
  auth-service:
    container_name: auth_service
    build:
      context: ./services/auth-service
    volumes:
      - ./services/auth-service/src:/var/www
    expose:
      - "9000"  # внутренний порт для nginx
    networks:
      - crm-network
    depends_on:
      - mysql
      - redis
      - rabbitmq

  # 👤 USER SERVICE — Менеджеры, сотрудники
  user-service:
    container_name: user_service
    build:
      context: ./services/user-service
    volumes:
      - ./services/user-service/src:/var/www
    #    env_file:
    #      - ./services/user-service/.env
    expose:
      - "9001"
    networks:
      - crm-network
    depends_on:
      - mysql

  # 📇 LEAD SERVICE — Клиенты, лиды, CRM-воронка
  lead-service:
    container_name: lead_service
    build:
      context: ./services/lead-service
    volumes:
      - ./services/lead-service/src:/var/www
    #    env_file:
    #      - ./services/lead-service/.env
    expose:
      - "9002"
    networks:
      - crm-network
    depends_on:
      - mysql

  # ✅ TASK SERVICE — Задачи и напоминания
  task-service:
    container_name: task_service
    build:
      context: ./services/task-service
    volumes:
      - ./services/task-service/src:/var/www
    #    env_file:
    #      - ./services/task-service/.env
    expose:
      - "9003"
    networks:
      - crm-network
    depends_on:
      - mysql
      - redis
      - rabbitmq

  # 📁 FILE SERVICE — Загрузка и хранение файлов через MinIO
  file-service:
    container_name: file_service
    build:
      context: ./services/file-service
    volumes:
      - ./services/file-service/src:/var/www
      - minio-data:/data
    #    env_file:
    #      - ./services/file-service/.env
    expose:
      - "9004"
    networks:
      - crm-network
    depends_on:
      - mysql
      - minio

  # 🔔 NOTIFICATION SERVICE — Email / Telegram / Очереди
  notification-service:
    container_name: notification_service
    build:
      context: ./services/notification-service
    volumes:
      - ./services/notification-service/src:/var/www
    #    env_file:
    #      - ./services/notification-service/.env
    expose:
      - "9005"
    networks:
      - crm-network
    depends_on:
      - rabbitmq

  # 🐬 MySQL (одна, многобазовая)
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"  # доступ с хоста (DBeaver и т.д.)
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - crm-network

  # 🧠 Redis — кеш и очереди
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"  # если нужен доступ снаружи
    networks:
      - crm-network

  # 🐇 RabbitMQ — брокер сообщений (с UI)
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    networks:
      - crm-network

  # ☁️ MinIO — хранилище файлов (аналог AWS S3)
  minio:
    container_name: minio_service
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"  # Web UI и API
    volumes:
      - minio-data:/data
    networks:
      - crm-network

# 🔄 Хранилища
volumes:
  mysql-data:
  minio-data:

# 🌐 Общая сеть для всех сервисов
networks:
  crm-network:
    driver: bridge
