FROM nginx:stable-alpine

# Удалим дефолтный конфиг и скопируем свой
#RUN rm /etc/nginx/conf.d/default.conf
#COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Копируем HTML-файлы (если есть, например, статика или index.html)
# COPY ./public /usr/share/nginx/html

# Открываем порт 80
EXPOSE 80
