name: Auto PR to dev from d-koshevoy

on:
  push:
    branches-ignore:
      - dev # игнорируем dev, чтобы не было рекурсии

jobs:
  auto-pr:
    if: github.actor == 'd-koshevoy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request to dev
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          
          # Защита от случая, если пуш был в ветку dev
          if [ "$BRANCH_NAME" == "dev" ]; then
            echo "Push was in dev, skipping PR creation."
            exit 0
          fi
          
          # Проверка, существует ли уже PR из этой ветки в dev
          EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --base dev --json number --jq '.[0].number')
          
          if [ -z "$EXISTING_PR" ]; then
            gh pr create \
              --title "Auto PR: $BRANCH_NAME → dev" \
              --body "Автоматическое создание PR от d-koshevoy" \
              --base dev \
              --head "$BRANCH_NAME"
            echo "Pull Request создан."
          else
            echo "PR уже существует: #$EXISTING_PR"
          fi
        shell: bash

      - name: Проверка
        run: echo "Ветка ${{ github.ref }} была запушена пользователем ${{ github.actor }}"
