name: CI on PR to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      # Optional: Basic PHP linting (syntax check)
      - name: PHP Syntax Check
        run: find . -type f -name "*.php" -exec php -l {} \;

      # Optional: Run PHP CodeSniffer (if you use it)
      # - name: Run PHP CodeSniffer
      #   run: vendor/bin/phpcs