name: Auto PR to dev

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Pull Request to dev
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CRM_SECRET }}
          title: 'Auto PR: ${{ github.ref_name }} → dev'
          commit-message: 'Auto PR from ${{ github.ref_name }}'
          base: dev
          branch: ${{ github.ref_name }}
          draft: false
