name: Auto PR to dev

on:
  push:
    branches:
      - d-koshevoy
    branches-ignore:
      - main
      - dev
permissions:
  contents: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CRM_SECRET }}
          title: 'Auto PR: ${{ github.ref_name }} → dev'
          commit-message: 'Auto PR from ${{ github.ref_name }}'
          base: dev
          branch: ${{ github.ref_name }}
          draft: false
